### ISSUE TITLE
Add support for include/exclude options

### ISSUE THREAD

**Issue by mdouglass** [mihaeu/cosmere#33]
I would like to add options to the configuration file include/exclude that allowed you to specify a set of globs to scan for markdown files (similar to the way include/exclude work in TypeScript's configuration files).
If a file is found, we would read the YAML frontmatter at the start of the document and used that to obtain the pageId/title values. 

We have a large monorepo and avoiding having a central list of documents would be nice to have. Admittedly, we could generate the pages list on the fly during the build if we had to, so I understand if you aren't interested in this feature.

That being said, I'm happy to do the work for it -- I just want to make sure you're open to the PR before I start on it.

**Comment by mihaeu** [comment]
I'm closing this issue for now, because it's quite old at this point. Sorry for not getting to it earlier. If this is still relevant let me know.

The reason why I initially decided against frontmatter was because it makes the markdown files harder to read and they just become pre-processed source material and aren't fun to read in the editor anymore (which is relevant for code information).

That being said, there's no reason to allow this in addition to the list in the config for those who prefer to publish this way. Let me know if there's still interest.
